export const midi_note_to_name = [
    undefined, // array starts with 0.
    undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined,
    undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined,
    "A0", "A#0", "B0",
    "C1", "C#1", "D1", "D#1", "E1", "F1", "F#1", "G1", "G#1", "A1", "A#1", "B1",
    "C2", "C#2", "D2", "D#2", "E2", "F2", "F#2", "G2", "G#2", "A2", "A#2", "B2",
    "C3", "C#3", "D3", "D#3", "E3", "F3", "F#3", "G3", "G#3", "A3", "A#3", "B3",
    "C4", "C#4", "D4", "D#4", "E4", "F4", "F#4", "G4", "G#4", "A4", "A#4", "B4",
    "C5", "C#5", "D5", "D#5", "E5", "F5", "F#5", "G5", "G#5", "A5", "A#5", "B5",
    "C6", "C#6", "D6", "D#6", "E6", "F6", "F#6", "G6", "G#6", "A6", "A#6", "B6",
    "C7", "C#7", "D7", "D#7", "E7", "F7", "F#7", "G7", "G#7", "A7", "A#7", "B7",
    "C8"
] as const

/**
 * Idea from repo's author. Code (constant) generated by Gemini.
 * 
 * @author Gemini
 */
export const chord_to_offset_dict: Map<string, number[]> = new Map([
    // --- Major Chords ---
    ["c_major", [0, 4, 7]],
    ["c_s_major", [1, 5, 8]],
    ["d_major", [2, 6, 9]],
    ["d_s_major", [3, 7, 10]],
    ["e_major", [4, 8, 11]],
    ["f_major", [5, 9, 0]],
    ["f_s_major", [6, 10, 1]],
    ["g_major", [7, 11, 2]],
    ["g_s_major", [8, 0, 3]],
    ["a_major", [9, 1, 4]],
    ["a_s_major", [10, 2, 5]],
    ["b_major", [11, 3, 6]],

    // --- Enharmonic Equivalents (Db = C#, Eb = D#, etc.) ---
    ["d_b_major", [1, 5, 8]],
    ["e_b_major", [3, 7, 10]],
    ["g_b_major", [6, 10, 1]],
    ["a_b_major", [8, 0, 3]],
    ["b_b_major", [10, 2, 5]],

    // --- Minor Chords ---
    ["c_minor", [0, 3, 7]],
    ["c_s_minor", [1, 4, 8]],
    ["d_minor", [2, 5, 9]],
    ["d_s_minor", [3, 6, 10]],
    ["e_minor", [4, 7, 11]],
    ["f_minor", [5, 8, 0]],
    ["f_s_minor", [6, 9, 1]],
    ["g_minor", [7, 10, 2]],
    ["g_s_minor", [8, 11, 3]],
    ["a_minor", [9, 0, 4]],
    ["a_s_minor", [10, 1, 5]],
    ["b_minor", [11, 2, 6]],

    // --- Enharmonic Equivalents ---
    ["d_b_minor", [1, 4, 8]],
    ["e_b_minor", [3, 6, 10]],
    ["g_b_minor", [6, 9, 1]],
    ["a_b_minor", [8, 11, 3]],
    ["b_b_minor", [10, 1, 5]]
]) 