# Generated by Gemini, adopted by the author.

import os
import re


def convert_flats_to_sharps():
    # The mapping of flats to sharps
    # Note: We use 's' instead of '#' because '#' can cause URL issues in web browsers
    flat_to_sharp = {
        'Db': 'Cs',
        'Eb': 'Ds',
        'Gb': 'Fs',
        'Ab': 'Gs',
        'Bb': 'As'
    }

    # Get the current directory where the script is running
    # Or replace with your specific path.
    folder_path = "public/instrument_sample/name_of_instrument/"

    print(f"Scanning folder: {os.path.abspath(folder_path)}")

    count = 0
    for filename in os.listdir(folder_path):
        # Match pattern like Ab4.mp3 or Bb2.wav
        # Group 1: Note (Ab), Group 2: Octave (4), Group 3: Extension (.mp3)
        match = re.match(r"^([A-G]b)(\d+)\.(mp3|wav|ogg)$", filename)

        if match:
            old_note = match.group(1)
            octave = match.group(2)
            extension = match.group(3)

            if old_note in flat_to_sharp:
                new_note = flat_to_sharp[old_note]
                new_filename = f"{new_note}{octave}.{extension}"

                old_path = os.path.join(folder_path, filename)
                new_path = os.path.join(folder_path, new_filename)

                try:
                    os.rename(old_path, new_path)
                    print(f"Renamed: {filename} -> {new_filename}")
                    count += 1
                except OSError as e:
                    print(f"Error renaming {filename}: {e}")

    print(f"\nTask finished. Total files renamed: {count}")


if __name__ == "__main__":
    convert_flats_to_sharps()
